# Generated by Django 2.0.7 on 2018-07-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at']},
        ),
    ]
