# Generated by Django 2.0.7 on 2018-07-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180716_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ManyToManyField(related_name='orders', to='shop.Order')),
            ],
            options={
                'abstract': False,
                'ordering': ['-updated_at'],
            },
        ),
    ]
