# Generated by Django 2.0.7 on 2018-07-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
