# Generated by Django 2.0.7 on 2018-07-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_bucket_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
