# Generated by Django 2.0.7 on 2018-07-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_bucket_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
