# Generated by Django 2.0.7 on 2018-07-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_bucket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
